// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPQMUCWDOR0WMM1fbcS7XMyomVTf8xdFU',
    appId: '1:1061435600391:web:6a5b757e623c5c5bb604a2',
    messagingSenderId: '1061435600391',
    projectId: 'propstake-67d27',
    authDomain: 'propstake-67d27.firebaseapp.com',
    storageBucket: 'propstake-67d27.firebasestorage.app',
    measurementId: 'G-M03Q26JBLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgVyKH1Z3Q65qP_GZGnEHCZ33qX_2i3GQ',
    appId: '1:1061435600391:android:3ed19717a9d5c8ffb604a2',
    messagingSenderId: '1061435600391',
    projectId: 'propstake-67d27',
    storageBucket: 'propstake-67d27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo70hlZFKyQ198Zw47MgrM2bdSsXyRRdY',
    appId: '1:1061435600391:ios:82216e85c09eb0c6b604a2',
    messagingSenderId: '1061435600391',
    projectId: 'propstake-67d27',
    storageBucket: 'propstake-67d27.firebasestorage.app',
    androidClientId: '1061435600391-7ngcbkhboeusj8cahk0djagshqb02bkh.apps.googleusercontent.com',
    iosClientId: '1061435600391-vbkgg27ft38mgh98i4dt7tvb8tc7j9r5.apps.googleusercontent.com',
    iosBundleId: 'com.prostake.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo70hlZFKyQ198Zw47MgrM2bdSsXyRRdY',
    appId: '1:1061435600391:ios:091d597f3cbd7538b604a2',
    messagingSenderId: '1061435600391',
    projectId: 'propstake-67d27',
    storageBucket: 'propstake-67d27.firebasestorage.app',
    androidClientId: '1061435600391-bpj04dhr27njan2ci910ff5ibtv7gsf4.apps.googleusercontent.com',
    iosClientId: '1061435600391-joeu690dkl1lbhpdjobpgk9eilgrnj3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.propstake',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPQMUCWDOR0WMM1fbcS7XMyomVTf8xdFU',
    appId: '1:1061435600391:web:e2bff4d75492d636b604a2',
    messagingSenderId: '1061435600391',
    projectId: 'propstake-67d27',
    authDomain: 'propstake-67d27.firebaseapp.com',
    storageBucket: 'propstake-67d27.firebasestorage.app',
    measurementId: 'G-2PJP432TX3',
  );

}